function toggle_div(bouton, id) { // On déclare la fonction toggle_div qui prend en param le bouton et un id
    var div = document.getElementById(id); // On récupère le div ciblé grâce à l'id
    if(div.style.display=="none") { // Si le div est masqué...
        div.style.display = "block"; // ... on l'affiche...
        bouton.innerHTML = "<img src=\"images/up-arrow.png\" width=\"25px\" margin-right=\"20px\">"; // ... et on change le contenu du bouton.
    } else { // S'il est visible...
        div.style.display = "none"; // ... on le masque...
        bouton.innerHTML = "<img src=\"images/angle-arrow-down.png\" width=\"25px\" margin-right=\"20px\">"; // ... et on change le contenu du bouton.
    }
}

